


// CUSTOMERS
export const FETCH_CUSTOMERS_REQUEST = "FETCH_CUSTOMERS_REQUEST";
export const FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";
export const FETCH_CUSTOMERS_SUCCESS_2 = "FETCH_CUSTOMERS_SUCCESS_2";
export const FETCH_CUSTOMERS_FAILURE = "FETCH_CUSTOMERS_FAILURE";
// CUSTOMERS LOADING
export const FETCH_CUSTOMER_REQUEST = "FETCH_CUSTOMER_REQUEST";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMER_FAILURE = "FETCH_CUSTOMER_FAILURE";


// USERS
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_SUCCESS_2 = "FETCH_USERS_SUCCESS_2";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
// USERS LOADING
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";


// USERS
export const FETCH_ADMINS_REQUEST = "FETCH_ADMINS_REQUEST";
export const FETCH_ADMINS_SUCCESS = "FETCH_ADMINS_SUCCESS";
export const FETCH_ADMINS_SUCCESS_2 = "FETCH_ADMINS_SUCCESS_2";
export const FETCH_ADMINS_FAILURE = "FETCH_ADMINS_FAILURE";
// ADMINS LOADING
export const FETCH_ADMIN_REQUEST = "FETCH_ADMIN_REQUEST";
export const FETCH_ADMIN_SUCCESS = "FETCH_ADMIN_SUCCESS";
export const FETCH_ADMIN_FAILURE = "FETCH_ADMIN_FAILURE";



// USERS
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_SUCCESS_2 = "FETCH_PRODUCTS_SUCCESS_2";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
// PRODUCTS LOADING
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";


// CATEGORY_PRODUCTS
export const FETCH_CATEGORY_PRODUCTS_REQUEST = "FETCH_CATEGORY_PRODUCTS_REQUEST";
export const FETCH_CATEGORY_PRODUCTS_SUCCESS = "FETCH_CATEGORY_PRODUCTS_SUCCESS";
export const FETCH_CATEGORY_PRODUCTS_SUCCESS_2 = "FETCH_CATEGORY_PRODUCTS_SUCCESS_2";
export const FETCH_CATEGORY_PRODUCTS_FAILURE = "FETCH_CATEGORY_PRODUCTS_FAILURE";
// CATEGORY_PRODUCTS LOADING
export const FETCH_CATEGORY_PRODUCT_REQUEST = "FETCH_CATEGORY_PRODUCT_REQUEST";
export const FETCH_CATEGORY_PRODUCT_SUCCESS = "FETCH_CATEGORY_PRODUCT_SUCCESS";
export const FETCH_CATEGORY_PRODUCT_FAILURE = "FETCH_CATEGORY_PRODUCT_FAILURE";


// BRAND_PRODUCTS
export const FETCH_BRAND_PRODUCTS_REQUEST = "FETCH_BRAND_PRODUCTS_REQUEST";
export const FETCH_BRAND_PRODUCTS_SUCCESS = "FETCH_BRAND_PRODUCTS_SUCCESS";
export const FETCH_BRAND_PRODUCTS_SUCCESS_2 = "FETCH_BRAND_PRODUCTS_SUCCESS_2";
export const FETCH_BRAND_PRODUCTS_FAILURE = "FETCH_BRAND_PRODUCTS_FAILURE";
// BRAND_PRODUCTS LOADING
export const FETCH_BRAND_PRODUCT_REQUEST = "FETCH_BRAND_PRODUCT_REQUEST";
export const FETCH_BRAND_PRODUCT_SUCCESS = "FETCH_BRAND_PRODUCT_SUCCESS";
export const FETCH_BRAND_PRODUCT_FAILURE = "FETCH_BRAND_PRODUCT_FAILURE";

// ORDER_PRODUCTS
export const FETCH_ORDER_PRODUCTS_REQUEST = "FETCH_ORDER_PRODUCTS_REQUEST";
export const FETCH_ORDER_PRODUCTS_SUCCESS = "FETCH_ORDER_PRODUCTS_SUCCESS";
export const FETCH_ORDER_PRODUCTS_SUCCESS_2 = "FETCH_ORDER_PRODUCTS_SUCCESS_2";
export const FETCH_ORDER_PRODUCTS_FAILURE = "FETCH_ORDER_PRODUCTS_FAILURE";
// ORDER_PRODUCTS LOADING
export const FETCH_ORDER_PRODUCT_REQUEST = "FETCH_ORDER_PRODUCT_REQUEST";
export const FETCH_ORDER_PRODUCT_SUCCESS = "FETCH_ORDER_PRODUCT_SUCCESS";
export const FETCH_ORDER_PRODUCT_FAILURE = "FETCH_ORDER_PRODUCT_FAILURE";


// ORDER_ITEMS
export const FETCH_ORDER_ITEMS_REQUEST = "FETCH_ORDER_ITEMS_REQUEST";
export const FETCH_ORDER_ITEMS_SUCCESS = "FETCH_ORDER_ITEMS_SUCCESS";
export const FETCH_ORDER_ITEMS_SUCCESS_2 = "FETCH_ORDER_ITEMS_SUCCESS_2";
export const FETCH_ORDER_ITEMS_FAILURE = "FETCH_ORDER_ITEMS_FAILURE";
// ORDER_ITEMS LOADING
export const FETCH_ORDER_ITEM_REQUEST = "FETCH_ORDER_ITEM_REQUEST";
export const FETCH_ORDER_ITEM_SUCCESS = "FETCH_ORDER_ITEM_SUCCESS";
export const FETCH_ORDER_ITEM_FAILURE = "FETCH_ORDER_ITEM_FAILURE";


// CHECKOUT_PRODUCTS
export const FETCH_CHECKOUT_PRODUCTS_REQUEST = "FETCH_CHECKOUT_PRODUCTS_REQUEST";
export const FETCH_CHECKOUT_PRODUCTS_SUCCESS = "FETCH_CHECKOUT_PRODUCTS_SUCCESS";
export const FETCH_CHECKOUT_PRODUCTS_SUCCESS_2 = "FETCH_CHECKOUT_PRODUCTS_SUCCESS_2";
export const FETCH_CHECKOUT_PRODUCTS_FAILURE = "FETCH_CHECKOUT_PRODUCTS_FAILURE";
// CHECKOUT_PRODUCTS LOADING
export const FETCH_CHECKOUT_PRODUCT_REQUEST = "FETCH_CHECKOUT_PRODUCT_REQUEST";
export const FETCH_CHECKOUT_PRODUCT_SUCCESS = "FETCH_CHECKOUT_PRODUCT_SUCCESS";
export const FETCH_CHECKOUT_PRODUCT_FAILURE = "FETCH_CHECKOUT_PRODUCT_FAILURE";



// BASKET_PRODUCTS
export const FETCH_BASKET_PRODUCTS_REQUEST = "FETCH_BASKET_PRODUCTS_REQUEST";
export const FETCH_BASKET_PRODUCTS_SUCCESS = "FETCH_BASKET_PRODUCTS_SUCCESS";
export const FETCH_BASKET_PRODUCTS_SUCCESS_2 = "FETCH_BASKET_PRODUCTS_SUCCESS_2";
export const FETCH_BASKET_PRODUCTS_FAILURE = "FETCH_BASKET_PRODUCTS_FAILURE";
// BASKET_PRODUCTS LOADING
export const FETCH_BASKET_PRODUCT_REQUEST = "FETCH_BASKET_PRODUCT_REQUEST";
export const FETCH_BASKET_PRODUCT_SUCCESS = "FETCH_BASKET_PRODUCT_SUCCESS";
export const FETCH_BASKET_PRODUCT_FAILURE = "FETCH_BASKET_PRODUCT_FAILURE";



// NOTIFICATIONS
export const FETCH_NOTIFICATIONS_REQUEST = "FETCH_NOTIFICATIONS_REQUEST";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_SUCCESS_2 = "FETCH_NOTIFICATIONS_SUCCESS_2";
export const FETCH_NOTIFICATIONS_FAILURE = "FETCH_NOTIFICATIONS_FAILURE";
// NOTIFICATIONS LOADING
export const FETCH_NOTIFICATION_REQUEST = "FETCH_NOTIFICATION_REQUEST";
export const FETCH_NOTIFICATION_SUCCESS = "FETCH_NOTIFICATION_SUCCESS";
export const FETCH_NOTIFICATION_FAILURE = "FETCH_NOTIFICATION_FAILURE";



// BASKET_PRODUCTS
export const FETCH_TRANSACTIONS_REQUEST = "FETCH_TRANSACTIONS_REQUEST";
export const FETCH_TRANSACTIONS_SUCCESS = "FETCH_TRANSACTIONS_SUCCESS";
export const FETCH_TRANSACTIONS_SUCCESS_2 = "FETCH_TRANSACTIONS_SUCCESS_2";
export const FETCH_TRANSACTIONS_FAILURE = "FETCH_TRANSACTIONS_FAILURE";
// TRANSACTIONS LOADING
export const FETCH_TRANSACTION_REQUEST = "FETCH_TRANSACTION_REQUEST";
export const FETCH_TRANSACTION_SUCCESS = "FETCH_TRANSACTION_SUCCESS";
export const FETCH_TRANSACTION_FAILURE = "FETCH_TRANSACTION_FAILURE";



// BLOGS
export const FETCH_BLOGS_REQUEST = "FETCH_BLOGS_REQUEST";
export const FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS";
export const FETCH_BLOGS_SUCCESS_2 = "FETCH_BLOGS_SUCCESS_2";
export const FETCH_BLOGS_FAILURE = "FETCH_BLOGS_FAILURE";
// BLOGS LOADING
export const FETCH_BLOG_REQUEST = "FETCH_BLOG_REQUEST";
export const FETCH_BLOG_SUCCESS = "FETCH_BLOG_SUCCESS";
export const FETCH_BLOG_FAILURE = "FETCH_BLOG_FAILURE";



// POSTAL_CODES
export const FETCH_POSTAL_CODES_REQUEST = "FETCH_POSTAL_CODES_REQUEST";
export const FETCH_POSTAL_CODES_SUCCESS = "FETCH_POSTAL_CODES_SUCCESS";
export const FETCH_POSTAL_CODES_SUCCESS_2 = "FETCH_POSTAL_CODES_SUCCESS_2";
export const FETCH_POSTAL_CODES_FAILURE = "FETCH_POSTAL_CODES_FAILURE";
// POSTAL_CODES LOADING
export const FETCH_POSTAL_CODE_REQUEST = "FETCH_POSTAL_CODE_REQUEST";
export const FETCH_POSTAL_CODE_SUCCESS = "FETCH_POSTAL_CODE_SUCCESS";
export const FETCH_POSTAL_CODE_FAILURE = "FETCH_POSTAL_CODE_FAILURE";




// select
export const SELECT_USER_CONVERSATION = "SELECT_USER_CONVERSATION";

// TRADUCTION DE LA LANGUE ;
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const changeLanguage = (language) => ({
  type: CHANGE_LANGUAGE,
  payload: language,
});